name: Project Automation

on:
  issues:
    types: [opened, assigned, labeled]
  pull_request:
    types: [opened, review_requested, approved, closed]

jobs:
  automate_project:
    runs-on: ubuntu-latest
    steps:
      - name: Move new issues to "To Do"
        if: github.event_name == 'issues' && github.event.action == 'opened'
        run: |
          gh project item update --id ${{ github.event.issue.node_id }} --field "Status" --value "To Do"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move issue to "In Progress" when assigned
        if: github.event_name == 'issues' && github.event.action == 'assigned'
        run: |
          gh project item update --id ${{ github.event.issue.node_id }} --field "Status" --value "In Progress"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move issue to "Blocked" when labeled as blocked
        if: github.event_name == 'issues' && github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'blocked')
        run: |
          gh project item update --id ${{ github.event.issue.node_id }} --field "Status" --value "Blocked"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move issue to "In Review" when PR is linked
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: |
          gh project item update --id ${{ github.event.pull_request.node_id }} --field "Status" --value "In Review"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move issue to "Testing" when PR is approved
        if: github.event_name == 'pull_request' && github.event.action == 'approved'
        run: |
          gh project item update --id ${{ github.event.pull_request.node_id }} --field "Status" --value "Testing"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move issue to "Done" when PR is merged
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: |
          gh project item update --id ${{ github.event.pull_request.node_id }} --field "Status" --value "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
